### ISSUE TITLE
Trouble with Petfinder v2 update on Squarespace

### ISSUE THREAD

**Issue by rmeziere** [cferdinandi/fetch-bugs#26]
Hi, I am trying to update my site with the v2 plugin. I've updated everything following the v1 video. Have not been able to get Petfinder to load since updating the js code injection. Key and secret have been updated for v2. Am I missing something obvious? 

https://www.bapbr.org/adoptable-dogs

Thanks!

**Comment by hikeleader** [comment]
same here..
https://www.realdogrescue.org/adopt

Do we need to add this code? If so where? 
<link rel="stylesheet" type="text/css" href="/css/fetch2.css">
<script src="/js/fetch2.js"></script>

**Comment by cferdinandi** [comment]
Two separate issues for these.

1. @rmeziere - you actually found a bug caused by a typo in the code. I just uploaded a fresh version with the bug fixed. You can download a fresh copy using the same download link you used for the original.

2. @hikeleader - your site does not appear to have Fetch loaded it on it at all. It looks like your site uses SquareSpace? If so, please follow the instructions for installing with SquareSpace available here: https://fetch.gomakethings.com/documentation/#setting-up-in-squarespace

**Comment by hikeleader** [comment]
A bit confused by that. The CSS and JS files are loaded. The code is on the page. Yes, i do have the petfinders iframe there as well while I work the rest out..but all of the other steps have been taken.

**Comment by cferdinandi** [comment]
You're trying to run Fetch _before_ the code is loaded. You include the Fetch code on line 501, but you're trying to run it on 390, before that code exists (JavaScript runs in order).

**Comment by hikeleader** [comment]
Did not seem to make a difference. I have the code in the header, line 42. I have "key-secret-shelter" at 390. The div line below that.

**Comment by hikeleader** [comment]
OK, figured it out. I was placing this on the page footer rather than just adding after the JS

 <script>
 new Fetch('[data-fetch]', {
		key: 'xxxxx',
		secret: 'Icccc',
		shelter: 'xxxx'
	});
</script>
